// The flat token artifact generated by packages/tokens/scripts/build-tokens.mjs
// and exposed as `@arkaes/tokens/tokens.json`.
//
// Declared here rather than inferred through `resolveJsonModule` for two
// reasons. The file is git-ignored and only exists after `pnpm --filter
// @arkaes/tokens generate`, so `tsc` should not have to read it. And the
// inferred literal type would make `description`/`reference` a union of
// per-token shapes (present on some tokens, absent on others) that is awkward
// to iterate under `strict`.
declare module "@arkaes/tokens/tokens.json" {
  const tokens: Record<
    string,
    {
      /** Fully dereferenced value, e.g. `#8f554d`. */
      value: string;
      /** DTCG `$type`, e.g. `color` or `dimension`. */
      type: string;
      /** Authoring tier — the directory under `packages/tokens/tokens/`. */
      tier: string;
      /** Value as authored, kept only while it still contains an `{alias}`. */
      reference?: string;
      description?: string;
    }
  >;
  export default tokens;
}
