// Generates CSS custom properties, a flat JSON artifact, and typed TS exports
// from the DTCG token sources in `tokens/`. Run as the first step of the
// package build (see package.json `generate`), before tsdown bundles/copies.
//
// Outputs (all git-ignored — regenerate with `pnpm --filter @arkaes/tokens generate`):
//   src/styles/tokens.generated.css  color + spacing custom properties (:root)
//   src/generated/tokens.json        flat { path: { value, type, description } }
//   src/generated/tokens.ts          typed `as const` map for programmatic use
import StyleDictionary from "style-dictionary";

const PREFIX = "ark";

/** Resolve a token's DTCG metadata regardless of parser normalization. */
function meta(token) {
  return {
    type: token.$type ?? token.type,
    description: token.$description ?? token.description ?? token.original?.$description,
  };
}

// Flat JSON keyed by dot-path — the shape an MCP server can read directly.
// `value` is fully resolved (references dereferenced) so consumers get the
// computed value; `type` and `description` come straight from the DTCG source.
StyleDictionary.registerFormat({
  name: "json/flat-dtcg",
  format({ dictionary }) {
    const out = {};
    for (const token of dictionary.allTokens) {
      const { type, description } = meta(token);
      out[token.path.join(".")] = {
        value: token.$value,
        type,
        ...(description ? { description } : {}),
      };
    }
    return JSON.stringify(out, null, 2) + "\n";
  },
});

// Typed `as const` export keyed by the same dot-path as the JSON artifact.
StyleDictionary.registerFormat({
  name: "typescript/flat-dtcg",
  format({ dictionary }) {
    const entries = dictionary.allTokens
      .map((t) => `  ${JSON.stringify(t.path.join("."))}: ${JSON.stringify(t.$value)},`)
      .join("\n");
    return [
      "// Generated by scripts/build-tokens.mjs from tokens/**/*.json — do not edit.",
      "export const tokens = {",
      entries,
      "} as const;",
      "",
      "export type TokenName = keyof typeof tokens;",
      "export type TokenValue = (typeof tokens)[TokenName];",
      "",
    ].join("\n");
  },
});

// Minimal transform set: kebab-case names with the `ark` prefix, values left
// exactly as authored (hex stays hex, rem stays rem, color-mix() passes
// through). `outputReferences` on the CSS format is what re-derives the
// var() chains — no value transform is wanted here.
const sharedPlatform = (buildPath, files) => ({
  transforms: ["name/kebab"],
  prefix: PREFIX,
  buildPath,
  files,
});

const sd = new StyleDictionary({
  source: ["tokens/**/*.json"],
  // DTCG source files use `$value` / `$type` / `$description`.
  usesDtcg: true,
  platforms: {
    css: sharedPlatform("src/styles/", [
      {
        destination: "tokens.generated.css",
        format: "css/variables",
        // Preserve the primitive -> semantic -> component tier structure as
        // var() chains. All tiers land in a single :root block.
        options: { outputReferences: true },
      },
    ]),
    json: sharedPlatform("src/generated/", [
      { destination: "tokens.json", format: "json/flat-dtcg" },
    ]),
    ts: sharedPlatform("src/generated/", [
      { destination: "tokens.ts", format: "typescript/flat-dtcg" },
    ]),
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
