// Generates CSS custom properties, a flat JSON artifact, and typed TS exports
// from the DTCG token sources in `tokens/`. Run as the first step of the
// package build (see package.json `generate`), before tsdown bundles/copies.
//
// Outputs (all git-ignored — regenerate with `pnpm --filter @arkaes/tokens generate`):
//   src/styles/tokens.generated.css  color + spacing custom properties (:root)
//   src/generated/tokens.json        flat { path: { value, type, tier, reference?, description? } }
//   src/generated/tokens.ts          typed `as const` map for programmatic use
import StyleDictionary from "style-dictionary";

const PREFIX = "ark";

/** Resolve a token's DTCG metadata regardless of parser normalization. */
function meta(token) {
  return {
    type: token.$type ?? token.type,
    description: token.$description ?? token.description ?? token.original?.$description,
  };
}

// A token's tier is the directory it was authored in (`tokens/<tier>/<file>.json`).
// All three tier files nest under the same top-level `"color"` key, so Style
// Dictionary collapses them into one `color.*` namespace and the source path is
// the only thing left that still knows where a token came from. Matched on the
// path tail so it works whether `filePath` is repo-relative or absolute.
const TIER_FROM_FILE_PATH = /(?:^|[\\/])tokens[\\/]([^\\/]+)[\\/][^\\/]+$/;

/** Which tier directory a token was authored in, e.g. `semantic`. */
function tierOf(token) {
  const filePath = token.filePath ?? "";
  const match = TIER_FROM_FILE_PATH.exec(filePath);
  if (match === null) {
    // Loud failure rather than a silent "unknown" tier: consumers group by this.
    throw new Error(
      `build-tokens: cannot derive a tier for "${token.path.join(".")}" from filePath ` +
        `"${filePath}". Token sources must live in tokens/<tier>/<file>.json.`,
    );
  }
  return match[1];
}

// The value exactly as authored, kept only while it still contains an `{alias}`.
// `value` below is fully dereferenced, so this is the only place the alias chain
// survives into the JSON. Covers a bare alias (`{color.neutral-0}`) as well as
// one inside an expression (`color-mix(in srgb, {color.neutral-700}, ...)`).
function referenceOf(token) {
  const authored = token.original?.$value ?? token.original?.value;
  return typeof authored === "string" && authored.includes("{") ? authored : undefined;
}

// Flat JSON keyed by dot-path — the shape an MCP server can read directly.
// `value` is fully resolved (references dereferenced) so consumers get the
// computed value; `type` and `description` come straight from the DTCG source.
// `tier` and `reference` let a consumer regroup tokens by authoring tier and
// show the alias chain that `value` flattens away — see the Foundations/Color
// story in apps/storybook.
StyleDictionary.registerFormat({
  name: "json/flat-dtcg",
  format({ dictionary }) {
    const out = {};
    for (const token of dictionary.allTokens) {
      const { type, description } = meta(token);
      const reference = referenceOf(token);
      out[token.path.join(".")] = {
        value: token.$value,
        type,
        tier: tierOf(token),
        ...(reference ? { reference } : {}),
        ...(description ? { description } : {}),
      };
    }
    return JSON.stringify(out, null, 2) + "\n";
  },
});

// Typed `as const` export keyed by the same dot-path as the JSON artifact.
StyleDictionary.registerFormat({
  name: "typescript/flat-dtcg",
  format({ dictionary }) {
    const entries = dictionary.allTokens
      .map((t) => `  ${JSON.stringify(t.path.join("."))}: ${JSON.stringify(t.$value)},`)
      .join("\n");
    return [
      "// Generated by scripts/build-tokens.mjs from tokens/**/*.json — do not edit.",
      "export const tokens = {",
      entries,
      "} as const;",
      "",
      "export type TokenName = keyof typeof tokens;",
      "export type TokenValue = (typeof tokens)[TokenName];",
      "",
    ].join("\n");
  },
});

// Minimal transform set: kebab-case names with the `ark` prefix, values left
// exactly as authored (hex stays hex, rem stays rem, color-mix() passes
// through). `outputReferences` on the CSS format is what re-derives the
// var() chains — no value transform is wanted here.
const sharedPlatform = (buildPath, files) => ({
  transforms: ["name/kebab"],
  prefix: PREFIX,
  buildPath,
  files,
});

const sd = new StyleDictionary({
  source: ["tokens/**/*.json"],
  // DTCG source files use `$value` / `$type` / `$description`.
  usesDtcg: true,
  platforms: {
    css: sharedPlatform("src/styles/", [
      {
        destination: "tokens.generated.css",
        format: "css/variables",
        // Preserve the primitive -> semantic -> component tier structure as
        // var() chains. All tiers land in a single :root block.
        options: { outputReferences: true },
      },
    ]),
    json: sharedPlatform("src/generated/", [
      { destination: "tokens.json", format: "json/flat-dtcg" },
    ]),
    ts: sharedPlatform("src/generated/", [
      { destination: "tokens.ts", format: "typescript/flat-dtcg" },
    ]),
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
