import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    // Generated by scripts/build-tokens.mjs (runs before tsdown via the
    // `build` script). Compiled so published consumers of
    // `@arkaes/tokens/generated` get JS + .d.ts, not raw TS.
    "generated/tokens": "src/generated/tokens.ts",
  },
  format: "esm",
  platform: "neutral",
  dts: true,
  clean: true,
  // CSS entrypoints (including the generated src/styles/tokens.generated.css)
  // and the flat JSON artifact are shipped as-is alongside the compiled output.
  // Copies src/<path> -> dist/<path>.
  copy: ["src/styles", "src/generated/tokens.json"],
});
